### ISSUE TITLE
add buttons for params when hitting smart contract APIs 

### ISSUE THREAD

**Issue by youraerials** [thencc/Irulan#12]
I find myself leaving values in the text field and not "committing" them because there is no CTA to let me know i need to hit RETURN to actually submit the argument or foreign asset, etc.  Can we add a simple button on the side that says "add"? I think this will make it obvious....

**Comment by spencercap** [comment]
resolved in https://github.com/thencc/Irulan/commit/9bf9e78b25e0e4cb2b97aee2640e0f91111c095b
