### ISSUE TITLE
Cannot search for contracts without an account

### ISSUE THREAD

**Issue by youraerials** [thencc/Irulan#30]
If you just go to Irulan.dev and try to search for a contract (e.g. 102439505), it fails with an unhelpful error.

It looks like you currently need to have a wallet linked before it will let you search.  Is this what we want?  If so, maybe we just need a little guardrail for things like this where we can see the search mechanism.

Certainly to query contracts we need a wallet and we don't want to become a block explorer per se, but maybe it's ok to allow search without a wallet?

**Comment by spencercap** [comment]
and redirect or give some meaningful message when going to /contact/[nothing] 
https://irulan.dev/testnet/contract

**Comment by spencercap** [comment]
re the original issue, yes, this is defo a bugo - this used to work!

**Comment by spencercap** [comment]
fixed w algonautjs pkg update in e76d556d2090c75a9c2af63a28ae92ecfad7db60
